= meta-laws-collection
:toc:

A collection of meta-laws you'll need to stay sane.

This is a curated list of https://en.wikipedia.org/wiki/List_of_eponymous_laws[the Wikipedia one].
Many thanks to them !

== The list

=== Betteridge's Law

https://en.wikipedia.org/wiki/Betteridge's_law_of_headlines[Betteridge's Law]

[sidebar]
Any headline that ends in a question mark can be answered by the word no.

=== Brandolini's Law

https://en.wikipedia.org/wiki/Brandolini%27s_law[Brandolini's Law]

[sidebar]
The amount of energy needed to refute bullshit is an order of magnitude bigger than that needed to produce it.

=== Carlson's Law

https://drvidyahattangadi.com/what-is-carlsons-law/[Carlson's Law]

[sidebar]
Interrupted work will be less effective and will take more time than  if it would completed in a continuous manner.

=== Chesterton's Fence

https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton's_fence[Chesterton's Fence]

[sidebar]
Reforms should not be made until the reasoning behind the existing state of affairs is understood.

=== Conway's Law

https://en.wikipedia.org/wiki/Conway%27s_law[Conway's Law]

[sidebar]
Any organization that designs a system will produce a design whose structure is a copy of the organization's communication structure.

=== Goodhart's Law

https://en.wikipedia.org/wiki/Goodhart%27s_law[Goodhart's Law]

[sidebar]
When a measure becomes a target, it ceases to be a good measure.

=== Hanlon's Razor

https://en.wikipedia.org/wiki/Hanlon%27s_razor[Hanlon's Razor]

[sidebar]
Never attribute to malice that which is adequately explained by stupidity.

=== Hawthorne Effect

https://en.wikipedia.org/wiki/Hawthorne_effect[Hawthorne Effect]

[sidebar]
Individuals can modify an aspect of their behavior in response to their awareness of being observed.

=== Hofstadter's Law

https://en.wikipedia.org/wiki/Hofstadter's_law[Hofstadter's Law]

[sidebar]
It always takes longer than you expect, even when you take into account Hofstadter's Law.

=== Peter Principle

https://en.wikipedia.org/wiki/Peter_principle[Peter Principle]

[sidebar]
In a hierarchy, every employee tends to rise to his level of incompetence.
