= meta-laws-collection
:toc:

A collection of meta-laws you'll need to stay sane.

This is a curated list of https://en.wikipedia.org/wiki/List_of_eponymous_laws[the Wikipedia one].
Many thanks to them !

== The list

=== Betteridge's Law

https://en.wikipedia.org/wiki/Betteridge%27s_law_of_headlines[Betteridge's Law]

[sidebar]
Any headline that ends in a question mark can be answered by the word no.

=== Brandolini's Law

https://en.wikipedia.org/wiki/Brandolini%27s_law[Brandolini's Law]

[sidebar]
The amount of energy needed to refute bullshit is an order of magnitude bigger than that needed to produce it.

=== Carlson's Law

https://drvidyahattangadi.com/what-is-carlsons-law/[Carlson's Law]

[sidebar]
Interrupted work will be less effective and will take more time than if it would completed in a continuous manner.

=== Chesterton's Fence

https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton's_fence[Chesterton's Fence]

[sidebar]
Reforms should not be made until the reasoning behind the existing state of affairs is understood.

=== Conway's Law

https://en.wikipedia.org/wiki/Conway%27s_law[Conway's Law]

[sidebar]
Any organization that designs a system will produce a design whose structure is a copy of the organization's communication structure.

=== Goodhart's Law

https://en.wikipedia.org/wiki/Goodhart%27s_law[Goodhart's Law]

[sidebar]
When a measure becomes a target, it ceases to be a good measure.

=== Hanlon's Razor

https://en.wikipedia.org/wiki/Hanlon%27s_razor[Hanlon's Razor]

[sidebar]
Never attribute to malice that which is adequately explained by stupidity.

=== Hawthorne Effect

https://en.wikipedia.org/wiki/Hawthorne_effect[Hawthorne Effect]

[sidebar]
Individuals can modify an aspect of their behavior in response to their awareness of being observed.

=== Hofstadter's Law

https://en.wikipedia.org/wiki/Hofstadter's_law[Hofstadter's Law]

[sidebar]
It always takes longer than you expect, even when you take into account Hofstadter's Law.

=== Hyrum's Law

https://www.hyrumslaw.com[Hyrum's Law]

[sidebar]
With a sufficient number of users of an API, it does not matter what you promise in the contract: all observable behaviors of your system will be depended on by somebody.

=== Lindy Effect

https://en.wikipedia.org/wiki/Lindy_effect[Lindy Effect]

[sidebar]
The longer a period something non-perishable has survived to exist or be used in the present, the longer its remaining life expectancy.

=== Murphy's Law

https://en.wikipedia.org/wiki/Murphy's_law[Murphy's Law]

[sidebar]
Anything that can go wrong will go wrong.

=== Parkinson's Law

https://en.wikipedia.org/wiki/Parkinson%27s_law[Parkinson's Law]

[sidebar]
The duration of work expands to fill its allotted time span, regardless of the amount of work to be done.


=== Peter Principle

https://en.wikipedia.org/wiki/Peter_principle[Peter Principle]

[sidebar]
In a hierarchy, every employee tends to rise to his level of incompetence.

=== Tesler's Law

https://en.wikipedia.org/wiki/Law_of_conservation_of_complexity[Tesler's Law]

[sidebar]
An application inherent complexity can never be removed, nor hidden, only dealt with trade-offs.
